//
//  OTProperties.h
//  RoughHandsFramework_Chat
//
//  Created by Sinhyub Kim on 11/1/12.
//  Copyright (c) 2012 Sinhyub Kim. All rights reserved.
//

#ifndef RoughHandsFramework_Chat_RHProperties_h
#define RoughHandsFramework_Chat_RHProperties_h

//#define SERVICE_VER
#define DEV_SERVICE_VER
//#define DEV_TESTGENERATOR_VER
//#define DEV_NOLOGIN_VER
//#define DEV_SNAPSHOTVIEWTEST_VER

#define FONTNAME_NAMSAN @"SeoulNamsan"
//#define FONTNAME_NAMSAN @"Helvetica Neue"

///////////////////////////////////////
// ROOT VIEW
#define ROOT_FRAME_X 0
#define ROOT_FRAME_Y 0
#define ROOT_FRAME_WIDTH 320
#define ROOT_FRAME_HEIGHT 500
///////////////////////////////////////

///////////////////////////////////////
// Main View
#define MAIN_FRAME_X ROOT_FRAME_X
#define MAIN_FRAME_Y ROOT_FRAME_Y
#define MAIN_FRAME_WIDTH ROOT_FRAME_WIDTH
#define MAIN_FRAME_HEIGHT ROOT_FRAME_HEIGHT

#define MENU_TABLE_FRAME_X ROOT_FRAME_X
#define MENU_TABLE_FRAME_Y ROOT_FRAME_Y
#define MENU_TABLE_FRAME_WIDTH 230
#define MENU_TABLE_FRAME_HEIGHT ROOT_FRAME_HEIGHT

static const float MENU_TABLE_OPEN_DELAY = 0.5;
static const float MENU_TABLE_CLOSE_DELAY = 0.3;
///////////////////////////////////////

///////////////////////////////////////
// Menu Table View
#define MENUCELL_TITLE_LOGO @"SPOT!"
#define MENUCELL_TITLE_MYPROFILE @"MY PROFILE"
#define MENUCELL_TITLE_FAVORITE @"FAVORITE"
#define MENUCELL_TITLE_PHYSICALSPOTMAP @"SPOT MAP"
#define MENUCELL_TITLE_LOGICALSPOTMAP @"VIRTUAL SPOT MAP"
#define MENUCELL_TITLE_USERMAP @"SPOT SPOT"
#define MENUCELL_TITLE_SIGNOUT @"SIGN OUT"
#define MENUCELL_TITLE_NULL @""

///////////////////////////////////////

///////////////////////////////////////
// NAVIGATION CONTROLLER VIEW
#define NAVIGATION_FRAME_X MAIN_FRAME_X
#define NAVIGATION_FRAME_Y MAIN_FRAME_Y
#define NAVIGATION_FRAME_WIDTH MAIN_FRAME_WIDTH
#define NAVIGATION_FRAME_HEIGHT MAIN_FRAME_HEIGHT
////////////////////////////////////////

///////////////////////////////////////
// NAVIGATION BAR VIEW
#define NAVIGATIONBAR_FRAME_X MAIN_FRAME_X
#define NAVIGATIONBAR_FRAME_Y MAIN_FRAME_Y
#define NAVIGATIONBAR_FRAME_WIDTH MAIN_FRAME_WIDTH
#define NAVIGATIONBAR_FRAME_HEIGHT 44
////////////////////////////////////////

////////////////////////////////////////
// SNAP MAP VIEW
#define CELL_FRAME_WIDTH SNAPMAP_FRAME_WIDTH
#define CELL_FRAME_HEIGHT (SNAPMAP_FRAME_HEIGHT-20)

#define DRAG_MEASUREMENT 100
#define DRAG_MEASUREMENT_MAP 100
#define POPUP_SLIDING_DELAY 5
#define HORIZONTAL_POPUPIMAGE_DISTANCE MAIN_FRAME_WIDTH
#define VERTICAL_POPUPIMAGE_DISTANCE MAIN_FRAME_HEIGHT

typedef enum SnapImageDirection {
    DIR_NONE = 0,
    DIR_RIGHT,
    DIR_DOWN,
    DIR_LEFT,
    DIR_UP,
} SnapImageDirection;

typedef enum SnapSubCellPosition {
    POSITION_TOPLEFT = 0,
    POSITION_TOPRIGHT = 1,
    POSITION_BOTTOMLEFT = 2,
    POSITION_BOTTOMRIGHT = 3,
    POSITION_MAX = 4,
} SnapSubCellPosition;

#define SNAPMAP_FRAME_X MAIN_FRAME_X
#define SNAPMAP_FRAME_Y (MAIN_FRAME_Y+NAVIGATIONBAR_FRAME_HEIGHT)
#define SNAPMAP_FRAME_WIDTH MAIN_FRAME_WIDTH
#define SNAPMAP_FRAME_HEIGHT (MAIN_FRAME_HEIGHT-NAVIGATIONBAR_FRAME_HEIGHT)

// Image Size related with Spot Class
#define IMAGE_RATIO_BASIC 0.75
#define IMAGE_RATIO_ANOTHER 0.6666
#define SNAP_INFO_WIDTH 40
#define SNAP_INFO_HEIGHT 40

#define SNAP_CLASS1_HEIGHT (CELL_FRAME_HEIGHT-20)/2 //SNAP_CLASS1_WIDTH*4/3 //200
#define SNAP_CLASS1_WIDTH SNAP_CLASS1_HEIGHT*3/4 //150


#define SNAP_CLASS2_WIDTH SNAP_CLASS1_WIDTH/2//75
#define SNAP_CLASS2_HEIGHT SNAP_CLASS1_HEIGHT/2//100

//#define SNAP_CLASS3_WIDTH 39
//#define SNAP_CLASS3_HEIGHT 52

#define MAX_DRAG_OFFSET_X SNAP_CLASS1_WIDTH*2;
#define MAX_DRAG_OFFSET_Y SNAP_CLASS1_HEIGHT*2;

// ImageView (inside of Spot Map View
#define SNAP_IMAGE_INTERVAL 0
#define SNAP_IMAGE_BORDER 1


#define POPUP_IMAGE_FRAME_X 40
#define POPUP_IMAGE_FRAME_Y 40
#define POPUP_IMAGE_FRAME_WIDTH (MAIN_FRAME_WIDTH-(2*POPUP_IMAGE_FRAME_X))
#define POPUP_IMAGE_FRAME_HEIGHT (POPUP_IMAGE_FRAME_WIDTH*3/2)

#define POPUP_GOTOPROFILE_BUTTON_WIDTH 120
#define POPUP_GOTOPROFILE_BUTTON_HEIGHT 30
#define POPUP_GOTOPROFILE_BUTTON_X (POPUP_IMAGE_FRAME_WIDTH-POPUP_GOTOPROFILE_BUTTON_WIDTH/2-10)
#define POPUP_GOTOPROFILE_BUTTON_Y (POPUP_IMAGE_FRAME_Y+POPUP_IMAGE_FRAME_HEIGHT-POPUP_GOTOPROFILE_BUTTON_HEIGHT/2)

////////////////////////////////////////////


///////////////////////////////////////////
// SPOT PROFILE VIEW
// Spot Profile View is opened as a (navigation Controller of SpotMapView)'s subview
#define SPOTPROFILE_FRAME_X MAIN_FRAME_X
#define SPOTPROFILE_FRAME_Y MAIN_FRAME_Y
#define SPOTPROFILE_FRAME_WIDTH MAIN_FRAME_WIDTH
#define SPOTPROFILE_FRAME_HEIGHT (MAIN_FRAME_HEIGHT-NAVIGATIONBAR_FRAME_HEIGHT)

#define SPOTPROFILE_SPOTKINGLABEL_DEFAULT @"KING"
#define SPOTPROFILE_SPOTKINGLABEL_X 30
#define SPOTPROFILE_SPOTKINGLABEL_Y 10
#define SPOTPROFILE_SPOTKINGLABEL_WIDTH (SPOTPROFILE_FRAME_WIDTH-SPOTPROFILE_SPOTKINGLABEL_X*3)/2
#define SPOTPROFILE_SPOTKINGLABEL_HEIGHT 30

#define SPOTPROFILE_SPOTKINGICON_WIDTH 40
#define SPOTPROFILE_SPOTKINGICON_HEIGHT 40
#define SPOTPROFILE_SPOTKINGICON_X (SPOTPROFILE_FRAME_WIDTH/2-SPOTPROFILE_SPOTKINGICON_WIDTH)/2
#define SPOTPROFILE_SPOTKINGICON_Y (SPOTPROFILE_SPOTKINGLABEL_Y+SPOTPROFILE_SPOTKINGLABEL_HEIGHT+5)

#define SPOTPROFILE_SPOTKINGNAMELABEL_DEFAULT @"???"
#define SPOTPROFILE_SPOTKINGNAMELABEL_X 30
#define SPOTPROFILE_SPOTKINGNAMELABEL_Y (SPOTPROFILE_SPOTKINGICON_Y+SPOTPROFILE_SPOTKINGICON_HEIGHT+5)
#define SPOTPROFILE_SPOTKINGNAMELABEL_WIDTH (SPOTPROFILE_FRAME_WIDTH-SPOTPROFILE_SPOTKINGLABEL_X*3)/2
#define SPOTPROFILE_SPOTKINGNAMELABEL_HEIGHT 30

#define SPOTPROFILE_SPOTQUEENLABEL_DEFAULT @"QUEEN"
#define SPOTPROFILE_SPOTQUEENLABEL_X (SPOTPROFILE_FRAME_WIDTH-SPOTPROFILE_SPOTKINGLABEL_X-SPOTPROFILE_SPOTQUEENLABEL_WIDTH)
#define SPOTPROFILE_SPOTQUEENLABEL_Y SPOTPROFILE_SPOTKINGLABEL_Y
#define SPOTPROFILE_SPOTQUEENLABEL_WIDTH SPOTPROFILE_SPOTKINGLABEL_WIDTH
#define SPOTPROFILE_SPOTQUEENLABEL_HEIGHT 30

#define SPOTPROFILE_SPOTQUEENICON_WIDTH 40
#define SPOTPROFILE_SPOTQUEENICON_HEIGHT 40
#define SPOTPROFILE_SPOTQUEENICON_X (SPOTPROFILE_FRAME_WIDTH-(SPOTPROFILE_FRAME_WIDTH/2-SPOTPROFILE_SPOTKINGICON_WIDTH)/2-SPOTPROFILE_SPOTQUEENICON_WIDTH)
#define SPOTPROFILE_SPOTQUEENICON_Y (SPOTPROFILE_SPOTKINGICON_Y)

#define SPOTPROFILE_SPOTQUEENNAMELABEL_DEFAULT @"???"
#define SPOTPROFILE_SPOTQUEENNAMELABEL_X SPOTPROFILE_SPOTQUEENLABEL_X
#define SPOTPROFILE_SPOTQUEENNAMELABEL_Y (SPOTPROFILE_SPOTQUEENICON_Y+SPOTPROFILE_SPOTQUEENICON_HEIGHT+5)
#define SPOTPROFILE_SPOTQUEENNAMELABEL_WIDTH SPOTPROFILE_SPOTQUEENLABEL_WIDTH
#define SPOTPROFILE_SPOTQUEENNAMELABEL_HEIGHT 30

#define SPOTPROFILE_SPOTKINGIMAGEVIEW_X (SPOTPROFILE_SPOTKINGNAMELABEL_X-10)
#define SPOTPROFILE_SPOTKINGIMAGEVIEW_Y (SPOTPROFILE_SPOTKINGNAMELABEL_Y+SPOTPROFILE_SPOTKINGNAMELABEL_HEIGHT+5)
#define SPOTPROFILE_SPOTKINGIMAGEVIEW_WIDTH (SPOTPROFILE_FRAME_WIDTH-SPOTPROFILE_SPOTKINGIMAGEVIEW_X*3)/2
#define SPOTPROFILE_SPOTKINGIMAGEVIEW_HEIGHT (SPOTPROFILE_SPOTKINGIMAGEVIEW_WIDTH*3/2)

#define SPOTPROFILE_SPOTQUEENIMAGEVIEW_X (SPOTPROFILE_FRAME_WIDTH-SPOTPROFILE_SPOTKINGIMAGEVIEW_X-SPOTPROFILE_SPOTQUEENIMAGEVIEW_WIDTH)
#define SPOTPROFILE_SPOTQUEENIMAGEVIEW_Y (SPOTPROFILE_SPOTQUEENNAMELABEL_Y+SPOTPROFILE_SPOTQUEENNAMELABEL_HEIGHT+5)
#define SPOTPROFILE_SPOTQUEENIMAGEVIEW_WIDTH SPOTPROFILE_SPOTKINGIMAGEVIEW_WIDTH
#define SPOTPROFILE_SPOTQUEENIMAGEVIEW_HEIGHT (SPOTPROFILE_SPOTQUEENIMAGEVIEW_WIDTH*3/2)

#define SPOTPROFILE_SPOTPOPULARITYLABEL_DEFAULT @"GRADE 0"
#define SPOTPROFILE_SPOTPOPULARITYLABEL_X 30
#define SPOTPROFILE_SPOTPOPULARITYLABEL_Y (SPOTPROFILE_SPOTKINGIMAGEVIEW_Y+SPOTPROFILE_SPOTKINGIMAGEVIEW_HEIGHT+10)
#define SPOTPROFILE_SPOTPOPULARITYLABEL_WIDTH (SPOTPROFILE_FRAME_WIDTH-SPOTPROFILE_SPOTPOPULARITYLABEL_X*2)
#define SPOTPROFILE_SPOTPOPULARITYLABEL_HEIGHT 20

#define SPOTPROFILE_SPOTDESCRIPTIONLABEL_X 20
#define SPOTPROFILE_SPOTDESCRIPTIONLABEL_Y (SPOTPROFILE_SPOTPOPULARITYLABEL_Y+SPOTPROFILE_SPOTPOPULARITYLABEL_HEIGHT+10)
#define SPOTPROFILE_SPOTDESCRIPTIONLABEL_WIDTH (SPOTPROFILE_FRAME_WIDTH-SPOTPROFILE_SPOTDESCRIPTIONLABEL_X*2)
#define SPOTPROFILE_SPOTDESCRIPTIONLABEL_HEIGHT 120


///////////////////////////////////////////
// POST VIEW
#define POSTSNAP_FRAME_X MAIN_FRAME_X
#define POSTSNAP_FRAME_Y MAIN_FRAME_Y
#define POSTSNAP_FRAME_WIDTH MAIN_FRAME_WIDTH
#define POSTSNAP_FRAME_HEIGHT MAIN_FRAME_HEIGHT

#define SELECTED_IMAGE_FRAME_X 10
#define SELECTED_IMAGE_FRAME_Y 10
#define SELECTED_IMAGE_FRAME_WIDTH 100
#define SELECTED_IMAGE_FRAME_HEIGHT 150

#define CHOOSESNAP_MODELLABEL_FRAME_X SELECTED_IMAGE_FRAME_X
#define CHOOSESNAP_MODELLABEL_FRAME_Y (SELECTED_IMAGE_FRAME_Y+SELECTED_IMAGE_FRAME_HEIGHT+5)
#define CHOOSESNAP_MODELLABEL_FRAME_WIDTH SELECTED_IMAGE_FRAME_WIDTH
#define CHOOSESNAP_MODELLABEL_FRAME_HEIGHT 30

#define CHOOSESNAP_BUTTON_FRAME_X 30
#define CHOOSESNAP_BUTTON_FRAME_Y 200
#define CHOOSESNAP_BUTTON_FRAME_WIDTH 260
#define CHOOSESNAP_BUTTON_FRAME_HEIGHT 30

#define CHOOSESPOT_BUTTON_FRAME_X 30
#define CHOOSESPOT_BUTTON_FRAME_Y 250
#define CHOOSESPOT_BUTTON_FRAME_WIDTH 260
#define CHOOSESPOT_BUTTON_FRAME_HEIGHT 30


#define POSTSNAP_BUTTON_FRAME_X 30
#define POSTSNAP_BUTTON_FRAME_Y 300
#define POSTSNAP_BUTTON_FRAME_WIDTH 260
#define POSTSNAP_BUTTON_FRAME_HEIGHT 25

#define DESCRIPTION_TEXTVIEW_FRAME_X 120
#define DESCRIPTION_TEXTVIEW_FRAME_Y 10
#define DESCRIPTION_TEXTVIEW_FRAME_WIDTH 190
#define DESCRIPTION_TEXTVIEW_FRAME_HEIGHT 150

#define DESCRIPTION_TEXTVIEW_PLACEHOLDER @" about this snap!\n where did you take?\n what items did you wear? "
#define ERROR_NO_SNAP_TO_POST @"Choose A Snap to Post"
#define ERROR_NO_PORTRAIT_ORIENTATION_SNAP_TO_POST @"Choose a Straight Up Snap to Post"
#define ERROR_NO_DESCRIPTION_TO_POST @"Write Description about THIS Snap"

///////////////////////////////////////////

///////////////////////////////////////////
// SNAPSHOT VIEW
#define SNAPSHOT_FRAME_X 0
#define SNAPSHOT_FRAME_Y 0
#define SNAPSHOT_FRAME_WIDTH MAIN_FRAME_WIDTH
#define SNAPSHOT_FRAME_HEIGHT (MAIN_FRAME_HEIGHT-NAVIGATIONBAR_FRAME_HEIGHT-20)

#define SNAPSHOT_SNAPSHOT_FRAME_X 25
#define SNAPSHOT_SNAPSHOT_FRAME_Y 30
#define SNAPSHOT_SNAPSHOT_FRAME_WIDTH 270
#define SNAPSHOT_SNAPSHOT_FRAME_HEIGHT 360

#define SNAPSHOT_PROFILE_FRAME_WIDTH 70
#define SNAPSHOT_PROFILE_FRAME_HEIGHT 70
#define SNAPSHOT_PROFILE_FRAME_X 10
#define SNAPSHOT_PROFILE_FRAME_Y (SNAPSHOT_SNAPSHOT_FRAME_Y+SNAPSHOT_SNAPSHOT_FRAME_HEIGHT-SNAPSHOT_PROFILE_FRAME_HEIGHT/2)

#define SNAPSHOT_USERNAME_FRAME_WIDTH 80
#define SNAPSHOT_USERNAME_FRAME_HEIGHT 30
#define SNAPSHOT_USERNAME_FRAME_X (SNAPSHOT_SNAPSHOT_FRAME_X+SNAPSHOT_SNAPSHOT_FRAME_WIDTH-SNAPSHOT_USERNAME_FRAME_WIDTH)
#define SNAPSHOT_USERNAME_FRAME_Y (SNAPSHOT_SNAPSHOT_FRAME_Y+SNAPSHOT_SNAPSHOT_FRAME_HEIGHT+10)

#define SNAPSHOT_DESCRIPTION_FRAME_X 20
#define SNAPSHOT_DESCRIPTION_FRAME_Y (SNAPSHOT_PROFILE_FRAME_Y+SNAPSHOT_PROFILE_FRAME_HEIGHT+20)
#define SNAPSHOT_DESCRIPTION_FRAME_WIDTH (SNAPSHOT_FRAME_WIDTH-SNAPSHOT_DESCRIPTION_FRAME_X*2)
#define SNAPSHOT_DESCRIPTION_FRAME_HEIGHT 70

#define SNAPSHOT_COMMENTTEXTFIELD_FRAME_WIDTH SNAPSHOT_FRAME_WIDTH*3/4
#define SNAPSHOT_COMMENTTEXTFIELD_FRAME_HEIGHT 30
#define SNAPSHOT_COMMENTTEXTFIELD_FRAME_X 0
#define SNAPSHOT_COMMENTTEXTFIELD_FRAME_Y (SNAPSHOT_FRAME_HEIGHT-SNAPSHOT_COMMENTTEXTFIELD_FRAME_HEIGHT-20)

#define SNAPSHOT_COMMENTBUTTON_FRAME_WIDTH (SNAPSHOT_FRAME_WIDTH-SNAPSHOT_COMMENTTEXTFIELD_FRAME_WIDTH)
#define SNAPSHOT_COMMENTBUTTON_FRAME_HEIGHT SNAPSHOT_COMMENTTEXTFIELD_FRAME_HEIGHT
#define SNAPSHOT_COMMENTBUTTON_FRAME_X SNAPSHOT_COMMENTTEXTFIELD_FRAME_WIDTH
#define SNAPSHOT_COMMENTBUTTON_FRAME_Y (SNAPSHOT_COMMENTTEXTFIELD_FRAME_Y)

#define SNAPSHOT_LIKEBUTTON_FRAME_WIDTH 70
#define SNAPSHOT_LIKEBUTTON_FRAME_HEIGHT SNAPSHOT_COMMENTBUTTON_FRAME_HEIGHT
#define SNAPSHOT_LIKEBUTTON_FRAME_X (SNAPSHOT_COMMENTBUTTON_FRAME_X-SNAPSHOT_LIKEBUTTON_FRAME_WIDTH-20)
#define SNAPSHOT_LIKEBUTTON_FRAME_Y SNAPSHOT_COMMENTBUTTON_FRAME_Y

#define SNAPSHOT_PROFILEIMAGE_FRAME_WIDTH 30
#define SNAPSHOT_PROFILEIMAGE_FRAME_HEIGHT 30

#define SNAPSHOT_PROFILENAME_WIDTH 150
#define SNAPSHOT_PROFILENAME_HEIGHT SNAPSHOT_PROFILEIMAGE_FRAME_HEIGHT

#define SNAPSHOT_COMMENT_FRAME_WIDTH SNAPSHOT_DESCRIPTION_FRAME_WIDTH
#define SNAPSHOT_COMMENT_FRAME_HEIGHT 30

#define SNAPSHOT_COMMENTBOX_FRAME_WIDTH SNAPSHOT_COMMENT_FRAME_WIDTH
#define SNAPSHOT_COMMENTBOX_FRAME_HEIGHT (SNAPSHOT_COMMENT_FRAME_HEIGHT*5)
#define SNAPSHOT_COMMENTBOX_FRAME_X (SNAPSHOT_FRAME_WIDTH-SNAPSHOT_COMMENTBOX_FRAME_WIDTH)/2
#define SNAPSHOT_COMMENTBOX_FRAME_Y (SNAPSHOT_DESCRIPTION_FRAME_Y+SNAPSHOT_DESCRIPTION_FRAME_HEIGHT+20)

///////////////////////////////////////////


///////////////////////////////////////////
// SearchPersonViewController
#define SEARCHPERSON_FRAME_X 0
#define SEARCHPERSON_FRAME_Y 0
#define SEARCHPERSON_FRAME_WIDTH MAIN_FRAME_WIDTH
#define SEARCHPERSON_FRAME_HEIGHT 44
///////////////////////////////////////////

///////////////////////////////////////////
#define USERPROFILE_PROFILESNAP_X 25
#define USERPROFILE_PROFILESNAP_Y 30
#define USERPROFILE_PROFILESNAP_WIDTH 270
#define USERPROFILE_PROFILESNAP_HEIGHT 360

#define USERPROFILE_PROFILEIMAGE_X 20
#define USERPROFILE_PROFILEIMAGE_Y (USERPROFILE_PROFILESNAP_Y+USERPROFILE_PROFILESNAP_HEIGHT+10)
#define USERPROFILE_PROFILEIMAGE_WIDTH 90
#define USERPROFILE_PROFILEIMAGE_HEIGHT 120

#define USERPROFILE_NICKNAME_X (USERPROFILE_PROFILEIMAGE_X+USERPROFILE_PROFILEIMAGE_WIDTH+30)
#define USERPROFILE_NICKNAME_Y (USERPROFILE_PROFILEIMAGE_Y)
#define USERPROFILE_NICKNAME_WIDTH 150
#define USERPROFILE_NICKNAME_HEIGHT 25

#define USERPROFILE_WORKINGPLACE_X USERPROFILE_NICKNAME_X
#define USERPROFILE_WORKINGPLACE_Y (USERPROFILE_NICKNAME_Y+USERPROFILE_NICKNAME_HEIGHT+10)
#define USERPROFILE_WORKINGPLACE_WIDTH 150
#define USERPROFILE_WORKINGPLACE_HEIGHT 25

#define USERPROFILE_GENDERIMAGE_X USERPROFILE_NICKNAME_X
#define USERPROFILE_GENDERIMAGE_Y (USERPROFILE_WORKINGPLACE_Y+USERPROFILE_WORKINGPLACE_HEIGHT+10)
#define USERPROFILE_GENDERIMAGE_WIDTH 25
#define USERPROFILE_GENDERIMAGE_HEIGHT 25

#define USERPROFILE_AGE_X (USERPROFILE_GENDERIMAGE_X + USERPROFILE_GENDERIMAGE_WIDTH + 25)
#define USERPROFILE_AGE_Y USERPROFILE_GENDERIMAGE_Y
#define USERPROFILE_AGE_WIDTH 100
#define USERPROFILE_AGE_HEIGHT 25

#define USERPROFILE_TABLE_X 0
#define USERPROFILE_TABLE_Y (USERPROFILE_PROFILEIMAGE_Y+USERPROFILE_PROFILEIMAGE_HEIGHT+5)
#define USERPROFILE_TABLE_WIDTH 320
#define USERPROFILE_TABLE_HEIGHT 300

///////////////////////////////////////////

#endif
