//
//  RHImageManager.h
//  RoughHandsFramework_Chat
//
//  Created by Sinhyub Kim on 10/22/12.
//  Copyright (c) 2012 Sinhyub Kim. All rights reserved.
//

// Keys For Image Manager
#define IMAGE_KEY_PICKER_SELECTED @"PICKER_IMAGE"
#define IMAGE_KEY_PICKER_SELECTED_LOCATION @"PICKER_IMAGE_LOCATION"
#define IMAGE_KEY_PLACEHHOLDER @"PLACEHOLDER"
#define IMAGE_KEY_BACKGROUNDTEXTURE @"BACKGROUNDDTEXTURE"

//#define IMAGE_KEY_BARBLACKBUTTON @"BARBLACKBUTTON"
//#define IMAGE_KEY_BARBLACKBUTTON_HIGHLIGHTED @"BARBLACKBUTTON_HIGHLIGHTED"
#define IMAGE_KEY_BUTTON @"BUTTON"
#define IMAGE_KEY_BUTTON_PRESSED @"BUTTON_PRESSED"

#define IMAGE_KEY_SIGNINBUTTON @"SIGNINBUTTON"
#define IMAGE_KEY_SIGNINBUTTON_PRESSED @"SIGNINBUTTON_PRESSED"
#define IMAGE_KEY_LIKEBUTTON @"LIKEBUTTON"
#define IMAGE_KEY_COMMENTBUTTON @"COMMENTBUTTON"
#define IMAGE_KEY_BACKGROUNDDEFAULT @"BACKGROUND_DEFAULT"

#define IMAGE_KEY_MALE @"MALE"
#define IMAGE_KEY_FEMALE @"FEMALE"
#define IMAGE_KEY_GENDER @"GENDER"

// ICON Images
#define IMAGE_KEY_LOGO @"MENUBARICON_LOGO"
#define IMAGE_KEY_MENUBARICON_LOCATION @"MENUBARICON_LOCATION"
#define IMAGE_KEY_MENUBARICON_PROFILE @"MENUBARICON_PROFILE"
#define IMAGE_KEY_MENUBARICON_SIGNOUT @"MENUBARICON_SIGNOUT"
#define IMAGE_KEY_MENUBARICON_USERMAP @"MENUBARICON_USERMAP"
#define IMAGE_KEY_KINGICON @"KINGICON"
#define IMAGE_KEY_QUEENICON @"QUEENICON"

#define IMAGE_KEY_MENUBAR @"MENUBAR"
#define IMAGE_KEY_MENUBARSECTION @"MENUBAR_SECTION"

#define IMAGE_KEY_MENU_OPENED @"MENU_OPENED"
#define IMAGE_KEY_MENU_CLOSED @"MENU_CLOSED"
//#define IMAGE_KEY_MENU_OPENED @"MENU_OPENED"
//#define IMAGE_KEY_MENU_CLOSED @"MENU_CLOSED"


// BUTON Images

#define IMAGE_KEY_SNAPMAPBOX @"ICON_SNAPMAPBOX"


// NEW
#define IMAGE_KEY_NAVBAR @"ICON_NAVBAR"
#define IMAGE_KEY_BAR320 @"ICON_BAR320"
#define IMAGE_KEY_NAVBAR320 @"ICON_NAVBAR320"
#define IMAGE_KEY_BAR640 @"ICON_BAR640"
#define IMAGE_KEY_MENUCELL @"ICON_MENUCELL"
#define IMAGE_KEY_LONGBUTTON @"ICON_LONGBUTTON"
#define IMAGE_KEY_FEMALEICON @"ICON_FEMALE"
#define IMAGE_KEY_MALEICON @"ICON_MALE"




@interface RHImageManager : NSObject
@property (strong, atomic) NSMutableDictionary* imageList;

// Singleton Methods
+ (id)allocWithZone:(NSZone *)zone;
- (id)copyWithZone:(NSZone *)zone;
+ (RHImageManager*) getInstance;
//


-(id)init;

-(void)pushImage:(UIImage*)image ForKey:(NSString*)key;
-(void)removeImageByKey:(NSString*)key;
-(UIImage*)getImageByKey:(NSString*)key;

@end


//static RHImageManager* s_ImageManager;